name: Build and release binaries
permissions:
  contents: write
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      name:
        description: "World"
        default: "Hello"
jobs:      
  build-x86:
    needs: test
    runs-on: ${{ matrix.os }}
    environment: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mywasm
            asset_name: mywasm
          - os: windows-latest
            artifact_name: mywasm.exe
            asset_name: mywasm.exe
    steps:
        - name: Cloning the repo
          uses: actions/checkout@v4

        - name: Install bun
          uses: oven-sh/setup-bun@v1
          
        - name: Install the modules
          run: |
            bun test
            make install
            make build
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.asset_name }}
            path: ${{ matrix.artifact_name }}

  release:
    name: Release the artifacts
    needs: build-x86
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v4
    
      - name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
          ls -alh
          touch a.txt
      
      - name: Move binaries to the working directory
        run: |
          mv mywasm.exe/mywasm.exe ./mywasm-window-amd64.exe
          mv mywasm/mywasm ./mywasm-linux-amd64
          ls

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.SHORT_SHA }}
          name: ${{ github.event.head_commit.message }}
          files: |
            mywasm-window-amd64.exe
            mywasm-linux-amd64
              
        
    
