name: Build and release binaries
on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      name:
        description: "World"
        default: "Hello"
jobs:
  build-x86:
    runs-on: ${{ matrix.os }}
    environment: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mywasm
            asset_name: ${{ github.event.repository.name }}-linux-amd64
          - os: windows-latest
            artifact_name: mywasm.exe
            asset_name: ${{ github.event.repository.name }}-windows-amd64.exe
    steps:
        - name: Cloning the repo
          uses: actions/checkout@v4

        - name: Install bun
          uses: oven-sh/setup-bun@v1
          
        - name: Install the modules
          run: |
            ls
            make install
            make build
            mv mywasm.exe mywasm || true
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.asset_name }}
            path: ${{ matrix.artifact_name }}
        
    
